//
//  AutoEquatable.swift
//  FTSDK
//
//  Created by John McIntosh on 5/1/17.
//  Copyright © 2017 FreeTextbooks. All rights reserved.
//

import Foundation


/// Placeholder protocol for requesting conformance to be generated by Sourcery
protocol AutoEquatable {}
